---
name: 'Egg Price Submission '
about: Collect egg prices information
title: ''
labels: ''
assignees: ''

---

name: Egg Price Submission
description: Submit egg prices you see at your store to help keep our tracker accurate.
title: "[Egg Price Submission] "
labels: ["egg-price"]
body:
  - type: input
    id: city-state
    attributes:
      label: City & state
      description: Where did you buy the eggs? (e.g., Eggville, Yolklahoma)
      placeholder: e.g., Eggville, Yolklahoma
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date you grabbed those eggs
      description: When did you buy the eggs? (e.g., 03/16/2025)
      placeholder: e.g., 03/16/2025
    validations:
      required: true
  - type: input
    id: price
    attributes:
      label: Price you paid (per dozen)
      description: How much did the eggs cost per dozen? (e.g., 3.99)
      placeholder: e.g., 3.99
    validations:
      required: true
  - type: input
    id: receipt
    attributes:
      label: Receipt or egg snap URL (optional)
      description: If you have a photo, upload it somewhere (e.g., Imgur) and paste the URL here.
      placeholder: e.g., https://imgur.com/your-image
    validations:
      required: false
